version: '3.8'

volumes:
  redisdata:
  mysqldata:

networks:
  default:
    driver: bridge

services:
  mysql:
    container_name: app_database
    image: mysql:9.0.1
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/lib/var/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "user_passbnIU3B4I4"
      MYSQL_DATABASE: "api"
      MYSQL_USER: "user_name2U34NBOUI4B"
      MYSQL_PASSWORD: "user_passbnIU3B4I4"

  redis:
    image: redis:alpine3.20
    container_name: app_redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - default