[package]
name = "command"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../app/core" }
dotenv = "0.15.0"
service = { path = "../app/service" }
types = { path = "../app/types" }
tokio = { version = "1", features = ["full"] }
chrono = "0.4.38"