[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-native-tls", "macros", "mysql", "time"] }