[package]
name = "types"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "types"
path = "src/prelude.rs"

[dependencies]
chrono = "0.4.38"
serde = "1.0.205"
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-native-tls", "macros", "mysql", "time"] }
