[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8", features = ["macros", "mysql", "time"] }
serde = { version = "1.0.217", features = ["derive"] }
utoipa = { version = "5.3.1", features = ["actix_extras"] }
actix-web = "4.8.0"
fcm = { git = "https://github.com/rj76/fcm-rust.git" }